# Generated by Django 2.2.12 on 2020-12-03 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_management', '0011_auto_20201119_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateNo', models.CharField(max_length=200)),
                ('driverLicenseNumber', models.CharField(max_length=200)),
                ('penaltyAmount', models.IntegerField(default=0)),
                ('penaltyReason', models.TextField()),
                ('paidStatus', models.BooleanField(default=False)),
                ('addedDate', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Employee')),
            ],
            options={
                'db_table': 'challan',
            },
        ),
    ]
