# Generated by Django 2.2.12 on 2020-11-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('addedDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='RankingCreteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rankingName', models.CharField(max_length=200)),
                ('addedDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ranking_creteria',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('empId', models.CharField(max_length=100)),
                ('mobileNo', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='emp-photo')),
                ('addedDate', models.DateTimeField(auto_now_add=True)),
                ('projectName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_management.Project')),
                ('reportingEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Employee')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Employee')),
                ('ratingCreteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.RankingCreteria')),
            ],
            options={
                'db_table': 'EmployeeRating',
                'unique_together': {('employee', 'ratingCreteria')},
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('empId', 'projectName')},
        ),
    ]
