# Generated by Django 2.2.12 on 2020-11-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_auto_20201106_1455'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='name_idx',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='Sumit', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='lastName',
            field=models.CharField(default='Tarwey', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='empId',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['firstName'], name='firstName_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['lastName'], name='lastName_idx'),
        ),
    ]
