# Generated by Django 2.2.12 on 2020-11-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0004_auto_20201106_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='projectName',
            new_name='project',
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('empId', 'project')},
        ),
    ]
