# Generated by Django 2.2.12 on 2020-11-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0005_auto_20201109_1348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeerating',
            unique_together=set(),
        ),
    ]
