# Generated by Django 2.2.12 on 2020-11-12 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0006_auto_20201111_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rankingcreteria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='employeerating',
            table='employee_rating',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.CreateModel(
            name='EmployeeProjectLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Project')),
            ],
            options={
                'db_table': 'employee_project_log',
            },
        ),
    ]
