# Generated by Django 2.2.12 on 2020-11-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0007_auto_20201112_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
