# Generated by Django 2.2.12 on 2020-11-12 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0008_employee_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Project'),
        ),
    ]
