# Generated by Django 2.2.12 on 2020-11-19 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0010_auto_20201119_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerating',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_rating', to='student_management.Employee'),
        ),
    ]
