# Generated by Django 2.2.12 on 2020-12-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0011_auto_20201119_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='emp-photo'),
        ),
    ]
